spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: # prod의 DB url
    driver-class-name: # prod의 DB에 맞는 driver
    username: # prod DB userName
    password: # prod DB password

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level: info
